version: 0.2

phases:
  install:
    commands:
      - npm install -g mocha
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - mocha lambda.js

artifacts:
  files:
    - '*.js'
    - node_modules/**/*